python plot_boxes.py staphylococcus-aureus/out_for_target1 target1 S.aureus
python plot_boxes.py staphylococcus-aureus/out_for_target2 target2 S.aureus
python plot_boxes.py staphylococcus-aureus/out_for_target3 target3 S.aureus
python plot_boxes.py staphylococcus-aureus/out_for_target4 target4 S.aureus
python plot_boxes.py staphylococcus-aureus/out_for_target5 target5 S.aureus
python plot_boxes.py staphylococcus-aureus/out_for_target6 target6 S.aureus
python plot_boxes.py staphylococcus-aureus/out_for_target7 target7 S.aureus
python plot_boxes.py staphylococcus-aureus/out_for_target8 target8 S.aureus
python plot_boxes.py staphylococcus-aureus/out_for_target9 target9 S.aureus
python plot_boxes.py staphylococcus-aureus/out_for_target10 target10 S.aureus
python plot_boxes.py staphylococcus-aureus/out_for_target11 target11 S.aureus
python plot_boxes.py staphylococcus-aureus/out_for_target12 target12 S.aureus
python plot_boxes.py staphylococcus-aureus/out_for_target13 target13 S.aureus
python plot_boxes.py staphylococcus-aureus/out_for_target14 target14 S.aureus
python plot_boxes.py staphylococcus-aureus/out_for_target15 target15 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target1 target1 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target2 target2 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target3 target3 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target4 target4 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target5 target5 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target6 target6 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target7 target7 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target8 target8 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target9 target9 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target10 target10 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target11 target11 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target12 target12 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target13 target13 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target14 target14 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target15 target15 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target16 target16 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target17 target17 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target18 target18 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target19 target19 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target20 target20 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target21 target21 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target22 target22 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target23 target23 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target24 target24 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target25 target25 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target26 target26 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target27 target27 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target28 target28 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target29 target29 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target30 target30 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target31 target31 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target32 target32 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target33 target33 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target34 target34 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target35 target35 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target36 target36 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target37 target37 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target38 target38 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target39 target39 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target40 target40 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target41 target41 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target42 target42 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target43 target43 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target44 target44 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target45 target45 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target46 target46 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target47 target47 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target48 target48 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target49 target49 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target50 target50 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target51 target51 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target52 target52 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target53 target53 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target54 target54 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target55 target55 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target56 target56 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target57 target57 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target58 target58 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target59 target59 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target60 target60 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target61 target61 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target62 target62 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target63 target63 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target64 target64 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target65 target65 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target66 target66 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target67 target67 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target68 target68 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target69 target69 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target70 target70 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target71 target71 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target72 target72 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target73 target73 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target74 target74 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target75 target75 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target76 target76 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target77 target77 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target78 target78 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target79 target79 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target80 target80 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target81 target81 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target82 target82 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target83 target83 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target84 target84 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target85 target85 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target86 target86 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target87 target87 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target88 target88 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target89 target89 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target90 target90 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target91 target91 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target92 target92 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target93 target93 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target94 target94 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target95 target95 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target96 target96 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target97 target97 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target98 target98 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target99 target99 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target100 target100 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target101 target101 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target102 target102 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target103 target103 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target104 target104 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target105 target105 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target106 target106 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target107 target107 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target108 target108 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target109 target109 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target110 target110 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target111 target111 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target112 target112 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target113 target113 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target114 target114 S.aureus
python plot_boxes.py rhodobacter-sphaeroides/out_for_target115 target115 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target1 target1 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target2 target2 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target3 target3 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target4 target4 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target5 target5 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target6 target6 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target7 target7 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target8 target8 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target9 target9 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target10 target10 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target11 target11 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target12 target12 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target13 target13 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target14 target14 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target15 target15 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target16 target16 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target17 target17 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target18 target18 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target19 target19 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target20 target20 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target21 target21 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target22 target22 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target23 target23 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target24 target24 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target25 target25 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target26 target26 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target27 target27 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target28 target28 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target29 target29 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target30 target30 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target31 target31 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target32 target32 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target33 target33 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target34 target34 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target35 target35 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target36 target36 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target37 target37 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target38 target38 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target39 target39 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target40 target40 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target41 target41 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target42 target42 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target43 target43 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target44 target44 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target45 target45 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target46 target46 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target47 target47 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target48 target48 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target49 target49 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target50 target50 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target51 target51 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target52 target52 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target53 target53 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target54 target54 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target55 target55 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target56 target56 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target57 target57 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target58 target58 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target59 target59 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target60 target60 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target61 target61 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target62 target62 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target63 target63 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target64 target64 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target65 target65 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target66 target66 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target67 target67 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target68 target68 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target69 target69 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target70 target70 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target71 target71 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target72 target72 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target73 target73 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target74 target74 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target75 target75 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target76 target76 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target77 target77 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target78 target78 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target79 target79 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target80 target80 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target81 target81 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target82 target82 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target83 target83 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target84 target84 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target85 target85 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target86 target86 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target87 target87 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target88 target88 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target89 target89 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target90 target90 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target91 target91 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target92 target92 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target93 target93 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target94 target94 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target95 target95 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target96 target96 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target97 target97 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target98 target98 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target99 target99 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target100 target100 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target101 target101 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target102 target102 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target103 target103 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target104 target104 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target105 target105 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target106 target106 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target107 target107 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target108 target108 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target109 target109 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target110 target110 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target111 target111 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target112 target112 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target113 target113 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target114 target114 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target115 target115 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target116 target116 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target117 target117 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target118 target118 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target119 target119 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target120 target120 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target121 target121 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target122 target122 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target123 target123 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target124 target124 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target125 target125 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target126 target126 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target127 target127 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target128 target128 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target129 target129 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target130 target130 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target131 target131 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target132 target132 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target133 target133 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target134 target134 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target135 target135 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target136 target136 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target137 target137 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target138 target138 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target139 target139 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target140 target140 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target141 target141 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target142 target142 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target143 target143 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target144 target144 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target145 target145 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target146 target146 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target147 target147 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target148 target148 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target149 target149 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target150 target150 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target151 target151 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target152 target152 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target153 target153 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target154 target154 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target155 target155 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target156 target156 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target157 target157 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target158 target158 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target159 target159 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target160 target160 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target161 target161 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target162 target162 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target163 target163 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target164 target164 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target165 target165 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target166 target166 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target167 target167 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target168 target168 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target169 target169 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target170 target170 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target171 target171 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target172 target172 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target173 target173 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target174 target174 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target175 target175 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target176 target176 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target177 target177 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target178 target178 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target179 target179 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target180 target180 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target181 target181 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target182 target182 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target183 target183 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target184 target184 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target185 target185 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target186 target186 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target187 target187 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target188 target188 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target189 target189 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target190 target190 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target191 target191 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target192 target192 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target193 target193 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target194 target194 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target195 target195 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target196 target196 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target197 target197 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target198 target198 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target199 target199 S.aureus
python plot_boxes.py homo-sapiens-chr14/out_for_target200 target200 S.aureus
